config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :threeplcentral_settings
  end
end

app/models/spree/address_decorator.rb
Spree::Address.class_eval do
  def to_threeplcentral
    name = "#{firstname} #{lastname}"

    {
      name: name,
      company_name: company || name || "None",
      phone_number1: phone,
      address: {
        address1: address1, address2: address2, city: city, state: state.abbr,
        zip: zipcode, country: country.name
      }
    }
  end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :threeplcentral_api_key, :string
  preference :threeplcentral_login, :string
  preference :threeplcentral_password, :password
  preference :threeplcentral_user_login_id, :integer

  preference :threeplcentral_customer_id, :integer
  preference :threeplcentral_default_facility_id, :integer
  preference :threeplcentral_reference_number_prefix, :string
  preference :threeplcentral_billing_code, :string
end

app/models/spree/order_updater_decorator.rb
module ThreePLCentralOrderUpdater
  def update_payment_state
    initial_state = order.payment_state
    super.tap { create_3plcentral_order if initial_state != 'paid' && order.payment_state == 'paid' }
  end

  private

  def create_3plcentral_order
    order.shipments.send_to_3plcentral.each(&:send_to_3plcentral)
  end
end

Spree::OrderUpdater.class_eval do
  prepend ThreePLCentralOrderUpdater
end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do
  THREEPLCENTRAL_SUCCESS_RESPONSE = '1'.freeze

  scope :with_3plcentral, -> { joins(:shipping_methods).merge(Spree::ShippingMethod.with_3plcentral) }
  scope :sent_to_3plcentral, -> { where(sent_to_threeplcentral: true) }
  scope :not_sent_to_3plcentral, -> { where(sent_to_threeplcentral: [false, nil]) }
  scope :send_to_3plcentral, -> { distinct.merge(with_3plcentral).merge(not_sent_to_3plcentral) }

  def logger
    rails_logger = Rails.logger
    model_logger = super
    model_logger.is_a?(rails_logger.class) ? model_logger : rails_logger
  end

  def to_threeplcentral
    {
      trans_info: {
        reference_num: threeplcentral_reference_number,
      },
      ship_to: address.to_threeplcentral.merge(
        email_address1: order.email,
      ),
      shipping_instructions: shipping_method.to_threeplcentral,
      order_line_items: {
        order_line_item: manifest.map do |item|

          sku = item.line_item.variant.sku

          if item.part
            sku = item.variant.sku
          end

          {
            SKU: sku,
            qty: item.quantity,
            fulfillment_sale_price: item.line_item.price,
            fulfillment_discount_amount: item.line_item.promo_total
          }
        end
      },
      fulfillment_info: {
        fulfill_inv_shipping_and_handling: order.shipment_total
      }
    }
  end

  def threeplcentral_reference_number
    "#{Spree::Config.threeplcentral_reference_number_prefix}#{order.number}-#{number}"
  end

  def threeplcentral_order(reload = false)
    if reload || !instance_variable_defined?(:@threeplcentral_order)
      @threeplcentral_order = ThreePLCentral::Order
        .find(closed: 'Any', reference_num: threeplcentral_reference_number)
        .first
    end

    @threeplcentral_order
  end

  def send_to_3plcentral
    return if sent_to_threeplcentral
    logger.debug("3PLCentral Order ##{order.number} Shipment ##{number}")
    logger.info 'Creating shipment record'
    success = Rails.env.production? ? do_send_to_3plcentral : simulate_send_to_3plcentral
    update_column :sent_to_threeplcentral, success
  end

  def sync_3plcentral_state
    threeplcentral_order && \
      threeplcentral_order['tracking_number'] && \
      update(tracking: threeplcentral_order['tracking_number']) && \
      ship!
  end

  private

  def do_send_to_3plcentral
    serialized = to_threeplcentral
    logger.info("Sending shipment: #{serialized}")
    response = ThreePLCentral::Order.create(serialized)
    (response.body[:int32] == THREEPLCENTRAL_SUCCESS_RESPONSE).tap do |success|
      logger.error("Error creating shipment: #{response.body}") unless success
    end
  rescue => ex
    logger.error("Error creating shipment: #{ex.message}")
    false
  end

  def simulate_send_to_3plcentral
    logger.debug("Not in production environment, skipping shipment creation. Would have sent: #{to_threeplcentral}")
    true
  end
end

app/models/spree/shipping_category_decorator.rb
Spree::ShippingCategory.class_eval do
  scope :with_3plcentral, -> { where(threeplcentral_create: true) }
end

app/models/spree/shipping_method_decorator.rb
Spree::ShippingMethod.class_eval do
  scope :with_3plcentral, -> { joins(:shipping_categories).merge(Spree::ShippingCategory.with_3plcentral) }

  def to_threeplcentral
    {
      carrier: carrier || 'N/A',
      mode: admin_name,
      billing_code: Spree::Config.threeplcentral_billing_code
    }
  end

  private

  def carrier
    admin_name.split(' ').first
  end
end

app/controllers/spree/admin/threeplcentral_settings_controller.rb
module Spree
  module Admin
    class ThreePLCentralSettingsController < Spree::Admin::BaseController
      CREDENTIAL_FIELDS = [
        :threeplcentral_api_key,
        :threeplcentral_login,
        :threeplcentral_password,
        :threeplcentral_user_login_id
      ].freeze
      PREFERENCE_FIELDS = [
        :threeplcentral_customer_id,
        :threeplcentral_default_facility_id,
        :threeplcentral_reference_number_prefix,
        :threeplcentral_billing_code
      ].freeze

      before_action :set_fields, :set_shipping_categories

      def edit
      end

      def update
        params.slice(*@fields).each do |name, value|
          Spree::Config[name] = value if Spree::Config.has_preference? name
        end

        @error = Spree3PLCentral.test

        if @error
          render :edit
        else
          flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:threeplcentral_settings))
          redirect_to edit_admin_threeplcentral_settings_path
        end
      end

      private

      def set_fields
        @credential_fields = CREDENTIAL_FIELDS
        @preference_fields = PREFERENCE_FIELDS
        @fields = (@credential_fields + @preference_fields).freeze
        @savon = ThreePLCentral.savon_config
      end

      def set_shipping_categories
        @shipping_categories = Spree::ShippingCategory.with_3plcentral
      end
    end
  end
end

app/views/spree/admin/shipping_categories/_edit_3plcentral.html.erb
<div data-hook="admin_shipping_categories_form_3plcentral">
  <div class="form-group">
    <%= f.label :threeplcentral_create do %>
      <%= f.check_box :threeplcentral_create %>
      <%= Spree.t(:threeplcentral_create) %>
    <%- end %>
  </div>
</div>

app/views/spree/admin/threeplcentral_settings/edit.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t(:threeplcentral_settings) %>
<% end %>

<div id="preferences" data-hook>
  <%- if @error %>
    <div class="alert alert-danger">
      <%= Spree.t(:threeplcentral_api_error, message: @error.message) %>
    </div>
  <%- end %>

  <h6>WSDL URL: <%=@savon[:wsdl] %></h6>
  <%= form_tag admin_threeplcentral_settings_path, method: :put do %>
    <div class="row">
      <div class="col-md-6">
        <fieldset class="no-border-bottom">
          <legend><%= Spree.t(:threeplcentral_api_credentials)%></legend>
          <%- @credential_fields.each do |key| %>
            <%- type = Spree::Config.preference_type(key) %>
            <div class="form-group">
              <%= label_tag(key, Spree.t(key)) + tag(:br) if type != :boolean %>
              <%= preference_field_tag(key, Spree::Config[key], type: type) %>
              <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
            </div>
          <% end %>
        </fieldset>
      </div>

      <div class="col-md-6">
        <fieldset class="no-border-bottom">
          <legend><%= Spree.t(:threeplcentral_preferences)%></legend>
          <%- @preference_fields.each do |key| %>
            <%- type = Spree::Config.preference_type(key) %>
            <div class="form-group">
              <%= label_tag(key, Spree.t(key)) + tag(:br) if type != :boolean %>
              <%= preference_field_tag(key, Spree::Config[key], type: type) %>
              <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
            </div>
          <% end %>
        </fieldset>
      </div>
    </div>

    <div class="form-buttons" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), edit_admin_threeplcentral_settings_url, icon: 'delete' %>
    </div>
  <% end %>

  <br />
  <br />
  <div class="row">
    <div class="col-md-12">
      <%- if @shipping_categories %>
        3PLCentral sync is enabled for the following shipping categories:
        <ul>
          <%- @shipping_categories.each do |cat| %>
            <li><%= link_to cat.name, edit_admin_shipping_category_path(cat) %></li>
          <%- end %>
        </ul>
      <%- else %>
        3PLCentral sync is not enabled for any shipping categories.&nbsp;
      <%- end %>
      Enable 3PLCentral sync on the <%=link_to 'shipping categories admin page', admin_shipping_categories_path %>.
    </div>
  </div>
</div>